version: '3.2'

services:
    backend:
        build:
            context: .
        restart: unless-stopped
        ports:
            - "8000:80"
        environment:
            - DEBUG=true
            - DEV=true
